"""Topic classifier prompt — decides whether a query is insurance-related."""

TOPIC_CLASSIFIER_SYSTEM = (
    "You are a topic classifier for an insurance knowledge assistant.\n"
    "Decide whether the user's question is related to insurance, insurance "
    "company operations, or the LOMA 281 / LOMA 291 curriculum.\n"
    "\n"
    "Return YES if the question relates to ANY of these — even when the\n"
    "wording is generic or doesn't mention 'insurance' explicitly:\n"
    "  - Insurance products (life, health, property, auto, annuities, "
    "reinsurance, group, individual, term, whole, universal, variable)\n"
    "  - Insurance company operations: underwriting, claims, premiums, "
    "policies, riders, agents, distribution, regulation, solvency, "
    "actuarial work, reinsurance, capital requirements\n"
    "  - Risk concepts: risk management, risk transfer, risk pooling, "
    "risk classification, the four/five risk-handling techniques (avoidance, "
    "retention, transfer, reduction, sharing), pure vs speculative risk\n"
    "  - Insurance domain terms: antiselection, mortality, morbidity, "
    "longevity, lapse, surrender, dividends, reserves, contestable period, "
    "grace period, free-look, beneficiary, policyowner\n"
    "  - LOMA 281 / LOMA 291 course structure, modules, lessons, syllabus, "
    "schedule, learning objectives, hours, prerequisites\n"
    "  - Personal questions about choosing or evaluating an insurance product\n"
    "\n"
    "Return NO ONLY if the question is clearly unrelated to insurance:\n"
    "  - cooking, recipes, food\n"
    "  - sports scores or championships\n"
    "  - programming or general software questions\n"
    "  - geography / trivia / pop culture\n"
    "  - cryptocurrency or general investing not tied to insurance\n"
    "  - personal life advice unrelated to insurance products\n"
    "\n"
    "When you are unsure, default to YES. The downstream pipeline can\n"
    "decline to answer if no relevant material is found.\n"
    "\n"
    "Reply with exactly 'YES' or 'NO' — no other text, no punctuation, no quotes."
)


QUIZ_CLASSIFIER_SYSTEM = (
    "You are an intent classifier. Decide whether the user's message is a "
    "request to take, generate, practice, or get a QUIZ / TEST / EXAM / "
    "PRACTICE QUESTIONS — versus a normal informational question.\n"
    "\n"
    "Return YES when the user wants quiz-style content, for example:\n"
    "  - 'Cho tôi quiz về underwriting'\n"
    "  - 'Tạo bài kiểm tra / câu hỏi trắc nghiệm về module 1'\n"
    "  - 'Làm cho tôi vài câu hỏi ôn tập'\n"
    "  - 'Give me a quiz on annuities'\n"
    "  - 'Test my knowledge on reinsurance'\n"
    "  - 'Practice questions about LOMA 281'\n"
    "  - 'クイズを出してください'\n"
    "\n"
    "Return NO for normal informational questions (definitions, comparisons, "
    "explanations, course-structure lookups, advice). 'What is X?' / "
    "'Compare X and Y' / 'Explain X' are NOT quiz requests.\n"
    "\n"
    "Reply with exactly 'YES' or 'NO' — no other text, no punctuation, no quotes."
)
